### ISSUE TITLE
Document how to create table with correct schema

### ISSUE THREAD

**Issue by wjones127** [delta-incubator/dynamodb-lock-rs#2]
It seems like this requires a dynamodb table to created with a particular name for hash and range key, but those aren't described in the docs. Users will get a generic `"The provided key element does not match the schema"`  if they mess this up, without knowing what the correct schema is.

https://delta-users.slack.com/archives/C013LCAEB98/p1695725222273019

**Comment by wjones127** [comment]
This might be it: https://github.com/delta-io/kafka-delta-ingest#writing-to-s3

**Comment by rtyler** [comment]
Here's a [terraform example](https://github.com/buoyant-data/oxbow/blob/main/deployment.tf#L126-L138) from a real production use-case
